In [11]:
import numpy as np
import pandas as pd
import graphlab
from sklearn.model_selection import train_test_split

In [12]:
def get_numpy_data_sframe(data_sframe, features, output):
    data_sframe['constant'] = 1 # add a constant column to an SFrame
    # prepend variable 'constant' to the features list
    features = ['constant'] + features
    # select the columns of data_SFrame given by the ‘features’ list into the SFrame ‘features_sframe’

    # this will convert the features_sframe into a numpy matrix with GraphLab Create >= 1.7!!
    features_matrix = data_sframe[features].to_numpy()
    # assign the column of data_sframe associated with the target to the variable ‘output_sarray’

    # this will convert the SArray into a numpy array:
    output_array = data_sframe[output].to_numpy() # GraphLab Create>= 1.7!!
    print(output_array.shape)
    return features_matrix, output_array

In [13]:
'''
Next write a function that takes a data set, a list of features 
(e.g. [‘sqft_living’, ‘bedrooms’]), to be used as inputs, and a name of 
the output (e.g. ‘price’). This function should return a features_matrix 
(2D array) consisting of first a column of ones followed by columns 
containing the values of the input features in the data set in the same 
order as the input list. It should also return an output_array which is 
an array of the values of the output in the data set (e.g. ‘price’). 
e.g. if you’re using SFrames and numpy you can complete the following 
function:
'''

# df -> data frame
# features -> required features names (list)
# output -> output feature name (list)
def get_numpy_data(df, features, output):
    
    df['constant'] = 1 # add a constant column to an SFrame
    # prepend variable 'constant' to the features list
    features = ['constant'] + features
    # select the columns of data_SFrame given by the ‘features’ list into the SFrame ‘features_sframe’

    # this will convert the features_sframe into a numpy matrix with GraphLab Create >= 1.7!!
    features_matrix = df[features].values
    # assign the column of data_sframe associated with the target to the variable ‘output_sarray’

    # this will convert the SArray into a numpy array:
    output_array = df[output].values # GraphLab Create>= 1.7!!
    return(features_matrix, output_array)

In [14]:
'''
If the features matrix (including a column of 1s for the constant) is 
stored as a 2D array (or matrix) and the regression weights are stored 
as a 1D array then the predicted output is just the dot product between 
the features matrix and the weights (with the weights on the right). 
Write a function ‘predict_output’ which accepts a 2D array ‘feature_matrix’ 
and a 1D array ‘weights’ and returns a 1D array ‘predictions’. 
e.g. in python:
'''
def predict_outcome(features_matrix, weights):
    predictions = np.dot(features_matrix, weights)
    return predictions

In [15]:
'''
If we have a the values of a single input feature in an array 
‘feature’ and the prediction ‘errors’ (predictions - output) then the 
derivative of the regression cost function with respect to the weight of 
‘feature’ is just twice the dot product between ‘feature’ and ‘errors’. 
Write a function that accepts a ‘feature’ array and ‘error’ array and 
returns the ‘derivative’ (a single number). e.g. in python:
'''
def feature_derivative(errors, feature):
    print(errors.shape[0])
    print(feature.shape[0])
    derivative = 2 * np.dot(errors, feature)
    return derivative

In [16]:
def regresssion_gradient_descent(features_matrix, output, inital_weights, step_size, tolerance):
    converged = False
    weights = np.array(inital_weights)
    while not converged:
        predictions = predict_outcome(features_matrix, weights)
        errors = output - predictions
        print(errors.shape)
        print(output.shape)
        gradient_sum_squares = 0
        for i in range(len(weights)):
            feature = features_matrix[:,i]
            derivative = feature_derivative(errors, feature)
            gradient_sum_squares += derivative**2
            weights[i] += step_size * derivative
        gradient_magnitude = np.sqrt(gradient_sum_squares)
        #print(gradient_magnitude - tolerance)
        if gradient_magnitude < tolerance:
            converged = True
    return weights

In [17]:
dtype_dict = {'bathrooms':float, 'waterfront':int, 'sqft_above':int, 'sqft_living15':float, 'grade':int, 'yr_renovated':int, 'price':float, 'bedrooms':float, 'zipcode':str, 'long':float, 'sqft_lot15':float, 'sqft_living':float, 'floors':str, 'condition':int, 'lat':float, 'date':str, 'sqft_basement':int, 'yr_built':int, 'id':str, 'sqft_lot':int, 'view':int}
sales = pd.read_csv('kc_house_data.csv', dtype=dtype_dict)
X_train, X_test, y_train, y_test = train_test_split(sales, sales['price'], train_size=.8, random_state=0, test_size=.2)

# USING ON TRAIN DATA

In [18]:
simple_features = ['sqft_living']
my_output= 'price'
simple_feature_matrix, output = get_numpy_data(X_train, simple_features, my_output)
initial_weights = np.array([-47000., 1.])
step_size = 7e-12
tolerance = 2.5e7

/home/arsanuos/.local/lib/python2.7/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [19]:
simple_weights = regresssion_gradient_descent(simple_feature_matrix, output, initial_weights, step_size, tolerance)

(17290,)
(17290,)
17290
17290
17290
17290
(17290,)
(17290,)
17290
17290
17290
17290
(17290,)
(17290,)
17290
17290
17290
17290
(17290,)
(17290,)
17290
17290
17290
17290
(17290,)
(17290,)
17290
17290
17290
17290
(17290,)
(17290,)
17290
17290
17290
17290
(17290,)
(17290,)
17290
17290
17290
17290
(17290,)
(17290,)
17290
17290
17290
17290
(17290,)
(17290,)
17290
17290
17290
17290
(17290,)
(17290,)
17290
17290
17290
17290
(17290,)
(17290,)
17290
17290
17290
17290
(17290,)
(17290,)
17290
17290
17290
17290


In [20]:
simple_weights

array([-46999.88720259,    283.46383063])

# USING ON TEST DATA

In [20]:
simple_features = ['sqft_living']
my_output= 'price'
simple_feature_matrix, output = get_numpy_data(X_test, simple_features, my_output)
initial_weights = np.array([-47000., 1.])
step_size = 7e-12
tolerance = 2.5e7

/home/arsanuos/.local/lib/python2.7/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [21]:
simple_weights_test = regresssion_gradient_descent(simple_feature_matrix, output, initial_weights, step_size, tolerance)

KeyboardInterrupt: 

In [ ]:
simple_weights_test

# USING SFRAME

In [21]:
sales = graphlab.SFrame('kc_house_data.gl/')
train_data,test_data = sales.random_split(.8,seed=0)

In [22]:
simple_features = ['sqft_living']
my_output= 'price'
simple_feature_matrix, output = get_numpy_data_sframe(train_data, simple_features, my_output)
initial_weights = np.array([-47000., 1.])
step_size = 7e-12
tolerance = 2.5e7

(17384,)


In [23]:
simple_weights = regresssion_gradient_descent(simple_feature_matrix, output,initial_weights, step_size, tolerance)

(17384,)
(17384,)
17384
17384
17384
17384
(17384,)
(17384,)
17384
17384
17384
17384
(17384,)
(17384,)
17384
17384
17384
17384
(17384,)
(17384,)
17384
17384
17384
17384
(17384,)
(17384,)
17384
17384
17384
17384
(17384,)
(17384,)
17384
17384
17384
17384
(17384,)
(17384,)
17384
17384
17384
17384
(17384,)
(17384,)
17384
17384
17384
17384
(17384,)
(17384,)
17384
17384
17384
17384
(17384,)
(17384,)
17384
17384
17384
17384
(17384,)
(17384,)
17384
17384
17384
17384
(17384,)
(17384,)
17384
17384
17384
17384


In [24]:
simple_weights

array([-46999.88716555,    281.91211912])

In [25]:
simple_features = ['sqft_living']
my_output= 'price'
simple_feature_matrix, output = get_numpy_data_sframe(test_data, simple_features, my_output)
initial_weights = np.array([-47000., 1.])
step_size = 7e-12
tolerance = 2.5e7

(4229,)


In [26]:
simple_weights = regresssion_gradient_descent(simple_feature_matrix, output,initial_weights, step_size, tolerance)

(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
4229
4229
(4229,)
(4229,)
4229
4229
42

In [29]:
simple_weights

array([-46999.87880043,    282.35945337])

In [30]:
predictions = predict_outcome(simple_feature_matrix, simple_weights)
predictions[0]

356774.13951860263

# ADDING MORE FEATURES

In [33]:
model_features = ['sqft_living', 'sqft_living15']
my_output = 'price'
(feature_matrix, output) = get_numpy_data_sframe(test_data, model_features,my_output)
initial_weights = np.array([-100000., 1., 1.])
step_size = 4e-12
tolerance = 1e9

(4229,)


In [34]:
simple_weights = regresssion_gradient_descent(simple_feature_matrix, output,initial_weights, step_size, tolerance)

ValueError: shapes (4229,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)